CREATE TABLE UserDetails
(
	ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	FirstName NVARCHAR(50) NULL,
	LastName NVARCHAR(50) NULL,
	UserId NVARCHAR(128) NOT NULL
	CONSTRAINT fk_UserDetailsAspNetUsers FOREIGN KEY (UserId)
	REFERENCES AspNetUsers(Id)
)