//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assessments.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentLevel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssessmentLevel()
        {
            this.AssessmentCheckoffItems = new HashSet<AssessmentCheckoffItem>();
        }
    
        public int ID { get; set; }
        public int TranslationID { get; set; }
        public int LevelOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentCheckoffItem> AssessmentCheckoffItems { get; set; }
        public virtual Translation Translation { get; set; }
    }
}
