//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assessments.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentCheckoffItem
    {
        public int ID { get; set; }
        public int TranslationID { get; set; }
        public int AssessmentQuestionID { get; set; }
        public int AssessmentLevelID { get; set; }
        public int CheckOffItemOrder { get; set; }
    
        public virtual AssessmentQuestion AssessmentQuestion { get; set; }
        public virtual Translation Translation { get; set; }
        public virtual AssessmentLevel AssessmentLevel { get; set; }
    }
}
