//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assessments.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<AssessmentCategory> AssessmentCategories { get; set; }
        public virtual DbSet<AssessmentCheckoffItem> AssessmentCheckoffItems { get; set; }
        public virtual DbSet<AssessmentCollection> AssessmentCollections { get; set; }
        public virtual DbSet<AssessmentLevel> AssessmentLevels { get; set; }
        public virtual DbSet<AssessmentQuestion> AssessmentQuestions { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Translation> Translations { get; set; }
        public virtual DbSet<UserAssessmentCategory> UserAssessmentCategories { get; set; }
        public virtual DbSet<UserAssessmentCheckoffItem> UserAssessmentCheckoffItems { get; set; }
        public virtual DbSet<UserAssessmentQuestion> UserAssessmentQuestions { get; set; }
        public virtual DbSet<UserAssessment> UserAssessments { get; set; }
        public virtual DbSet<UserDetail> UserDetails { get; set; }
    }
}
