//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assessments.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssessmentQuestion()
        {
            this.AssessmentCheckoffItems = new HashSet<AssessmentCheckoffItem>();
            this.UserAssessmentQuestions = new HashSet<UserAssessmentQuestion>();
        }
    
        public int ID { get; set; }
        public int HeadingTranslationID { get; set; }
        public int AssessmentCategoryID { get; set; }
        public Nullable<int> BodyTranslationID { get; set; }
        public int QuestionOrder { get; set; }
        public string QuestionCode { get; set; }
    
        public virtual AssessmentCategory AssessmentCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentCheckoffItem> AssessmentCheckoffItems { get; set; }
        public virtual Translation Translation { get; set; }
        public virtual Translation Translation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserAssessmentQuestion> UserAssessmentQuestions { get; set; }
    }
}
