//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assessments.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Translation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Translation()
        {
            this.AssessmentCategories = new HashSet<AssessmentCategory>();
            this.AssessmentCheckoffItems = new HashSet<AssessmentCheckoffItem>();
            this.AssessmentCollections = new HashSet<AssessmentCollection>();
            this.AssessmentLevels = new HashSet<AssessmentLevel>();
            this.AssessmentQuestions = new HashSet<AssessmentQuestion>();
            this.AssessmentQuestions1 = new HashSet<AssessmentQuestion>();
        }
    
        public int ID { get; set; }
        public string EN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentCategory> AssessmentCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentCheckoffItem> AssessmentCheckoffItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentCollection> AssessmentCollections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentLevel> AssessmentLevels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentQuestion> AssessmentQuestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentQuestion> AssessmentQuestions1 { get; set; }
    }
}
