//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assessments.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAssessmentCheckoffItem
    {
        public int ID { get; set; }
        public int AssessmentCheckoffItemID { get; set; }
        public int UserAssessmentQuestionID { get; set; }
        public bool Checked { get; set; }
    
        public virtual AssessmentCheckoffItem AssessmentCheckoffItem { get; set; }
        public virtual UserAssessmentQuestion UserAssessmentQuestion { get; set; }
    }
}
