//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assessments.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAssessmentQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserAssessmentQuestion()
        {
            this.UserAssessmentCheckoffItems = new HashSet<UserAssessmentCheckoffItem>();
        }
    
        public int ID { get; set; }
        public int AssessmentQuestionID { get; set; }
        public int UserAssessmentCategoryID { get; set; }
        public string Comments { get; set; }
    
        public virtual AssessmentQuestion AssessmentQuestion { get; set; }
        public virtual UserAssessmentCategory UserAssessmentCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserAssessmentCheckoffItem> UserAssessmentCheckoffItems { get; set; }
    }
}
