//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assessments.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAssessmentCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserAssessmentCategory()
        {
            this.UserAssessmentQuestions = new HashSet<UserAssessmentQuestion>();
        }
    
        public int ID { get; set; }
        public int AssessmentCategoryID { get; set; }
        public int UserAssessmentID { get; set; }
    
        public virtual AssessmentCategory AssessmentCategory { get; set; }
        public virtual UserAssessment UserAssessment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserAssessmentQuestion> UserAssessmentQuestions { get; set; }
    }
}
